devip=10.210.20.85
devport=8077
devconnecttimeout=3500
devreadtimeout=30000
loadmode=1
user=default_user
authcode=12345678

sslon=no
sslprovider=
sslprotocol=
#sslcipherprotocol=TLS_RSA_WITH_AES_128_GCM_SHA256
#ssltrustx509provider=
#ssltrustmanagerfactoryalg=
#ssltrustmanagerfactoryprovider=

#### CER
#ssltrustcertpath="D:\\certs\\huawei\\crypto\\TLS-Certificate\\RSA\\CN=TLS_RSA_Client_chain.cer"

#### PFX
#ssltrustcertpath=/Users/aotiyou/certs/huawei/crypto/TLS-Certificate/RSA/CN=TLS_RSA_Client_no_pri.pfx
#ssltrustcertpassword=Ua6NuSCVPK/jxAlGFLNBeqp9oreUuAKD7HNZTkQffW0=

#### BKS
#ssltrustcertpath=/Users/aotiyou/certs/huawei/crypto/TLS-Certificate/RSA/CN=RSA_Server.bks
#ssltrustcertpassword=Ua6NuSCVPK/jxAlGFLNBeqp9oreUuAKD7HNZTkQffW0=
#ssltrustkeystoretype=BKS
#ssltrustkeystoreprovider=INFOSECV170

#### JKS
#ssltrustcertpath=/Users/aotiyou/certs/huawei/crypto/TLS-Certificate/RSA/CN=RSA_Server.jks
#ssltrustcertpassword=Ua6NuSCVPK/jxAlGFLNBeqp9oreUuAKD7HNZTkQffW0=

#ssltrustentryalias=
#sslclientmanagerfactoryalg=
#sslclientmanagerfactoryprovider=
#sslclientkeystoretype=
#sslclientkeystoreprovider=
#sslclientcertpath=/Users/aotiyou/certs/huawei/crypto/TLS-Certificate/RSA/CN=TLS_RSA_Client.pfx
#sslclientcertpassword=Ua6NuSCVPK/jxAlGFLNBeqp9oreUuAKD7HNZTkQffW0=

#logFile=/Users/aotiyou/infosec_project/huawei/java_agent/ucypher_jce.log
#logMaxSize=10
#logLevel=5
#logCount=10

